import { useEffect, useRef, useState } from 'react'
import { assetUrl } from '../assetUrl.js'

export function ImageComparison() {
  const [split, setSplit] = useState(50)
  return <div className="image-comparison">
    <div className="comparison-stage">
      <img className="reference-image" src={assetUrl('media/warehouse-reference.png')} alt="Warehouse rendered by Unreal Engine, camera 1, frame 600" width="512" height="512" fetchPriority="high" />
      <img className="neural-image" src={assetUrl('media/warehouse-neural.png')} alt="The same warehouse frame generated by MC-Shade" width="512" height="512" style={{ clipPath: `inset(0 0 0 ${split}%)` }} />
      <div className="comparison-divider" style={{ left: `${split}%` }} aria-hidden="true"><span>↔</span></div>
      <input className="comparison-range" type="range" min="0" max="100" value={split} onChange={e => setSplit(Number(e.target.value))} aria-label="Compare reference and neural rendering" aria-valuetext={`${split}% reference image, ${100 - split}% neural image`} />
    </div>
    <div className="comparison-key"><span>UE5 reference</span><span className="accent">MC-Shade</span></div>
  </div>
}

export function DemoFigure({
  id, number, title, subtitle,
  source = `media/${id}-loop.mp4`,
  poster = `media/${id}-poster.jpg`,
  leftLabel = 'UE5 reference',
  durationLabel = '12-SECOND EXCERPT',
  linkHref = `media/${id}-full.mp4`,
  linkLabel = 'Full sequence',
  caption = 'Frames 200–487 from a 998-frame autoregressive rollout. Reference and generated images share the same camera and frame. Playback restarts after frame 487; the loop is not seamless.',
}) {
  const videoRef = useRef(null)
  const [playing, setPlaying] = useState(false)
  const [failed, setFailed] = useState(false)
  const userPaused = useRef(false)
  const visible = useRef(false)
  useEffect(() => {
    const video = videoRef.current
    const media = window.matchMedia('(prefers-reduced-motion: reduce)')
    const sync = () => {
      if (visible.current && !document.hidden && !media.matches && !userPaused.current) {
        video.play().catch(() => setPlaying(false))
      } else video.pause()
    }
    const observer = new IntersectionObserver(entries => {
      visible.current = entries[0].isIntersecting
      sync()
    }, { threshold: 0.25 })
    observer.observe(video)
    document.addEventListener('visibilitychange', sync)
    media.addEventListener('change', sync)
    return () => {
      observer.disconnect()
      document.removeEventListener('visibilitychange', sync)
      media.removeEventListener('change', sync)
      video.pause()
    }
  }, [])
  const toggle = () => {
    const video = videoRef.current
    if (video.paused) {
      userPaused.current = false
      video.play().catch(() => setPlaying(false))
    } else {
      userPaused.current = true
      video.pause()
    }
  }
  return <figure className="demo-figure" data-demo={id}>
    <div className="figure-topline"><span>FIGURE {number} / {subtitle.toUpperCase()}</span><span>{durationLabel}</span></div>
    <div className="demo-labels"><span>{leftLabel}</span><span className="accent">MC-Shade</span></div>
    <video ref={videoRef} muted loop playsInline preload="metadata" src={assetUrl(source)} poster={assetUrl(poster)} aria-label={`${subtitle}: ${leftLabel} left, MC-Shade right`} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onError={() => setFailed(true)} />
    {failed && <p role="status" className="media-error">This excerpt could not load. Try opening the video below.</p>}
    <div className="demo-toolbar"><h3>{title}</h3><div><button className="button button-small" type="button" onClick={toggle} aria-label={`${playing ? 'Pause' : 'Play'} ${subtitle}`} disabled={failed}><span aria-hidden="true">{playing ? 'Ⅱ' : '▷'}</span>{playing ? 'Pause' : 'Play'}</button><a className="text-link" href={assetUrl(linkHref)} target="_blank" rel="noreferrer">{linkLabel} ↗</a></div></div>
    <figcaption>{caption}</figcaption>
  </figure>
}
